const API_BASE = "https://api.github.com";
const API_VERSION = "2026-03-10";
class GitHubServiceError extends Error { constructor(message,code="github_unavailable",status=null){super(message);this.name="GitHubServiceError";this.code=code;this.status=status;} }
function headers(token){return {Accept:"application/vnd.github+json","X-GitHub-Api-Version":API_VERSION,...(token?{Authorization:`Bearer ${token}`}:{})};}
async function githubFetch(path,{token,method="GET",headers:extra={},body,raw=false}={}){let response; try{response=await fetch(`${API_BASE}${path}`,{method,headers:{...headers(token),...extra},body,signal:AbortSignal.timeout(20000)});}catch(_){throw new GitHubServiceError("GitHub is currently unavailable. Please try again.","github_unavailable");} const text=await response.text(); if(!response.ok){let data=null;try{data=text?JSON.parse(text):null;}catch(_){data=null;} if(response.status===401)throw new GitHubServiceError("GitHub authorization has expired. Please reconnect GitHub.","github_unauthorized",401); if(response.status===403)throw new GitHubServiceError("GitHub denied access or the API rate limit was reached.","github_forbidden",403); if(response.status===404)throw new GitHubServiceError("GitHub repository or resource was not found.","github_not_found",404); throw new GitHubServiceError(data?.message||"GitHub request failed.","github_unavailable",response.status);} if(raw)return text; try{return text?JSON.parse(text):null;}catch(_){throw new GitHubServiceError("GitHub returned an unreadable response.","github_unavailable");}}
function buildOAuthUrl({state}){const params=new URLSearchParams({client_id:process.env.GITHUB_CLIENT_ID||"",redirect_uri:process.env.GITHUB_CALLBACK_URL||"http://localhost:5000/api/github/callback",scope:"repo",state,allow_signup:"true"});return `https://github.com/login/oauth/authorize?${params.toString()}`;}
async function exchangeCodeForToken(code){if(!process.env.GITHUB_CLIENT_ID||!process.env.GITHUB_CLIENT_SECRET)throw new GitHubServiceError("GitHub OAuth is not configured on the server.","github_not_configured",503);let response;try{response=await fetch("https://github.com/login/oauth/access_token",{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({client_id:process.env.GITHUB_CLIENT_ID,client_secret:process.env.GITHUB_CLIENT_SECRET,code,redirect_uri:process.env.GITHUB_CALLBACK_URL||"http://localhost:5000/api/github/callback"}),signal:AbortSignal.timeout(20000)});}catch(_){throw new GitHubServiceError("GitHub OAuth is currently unavailable.","github_unavailable");} const data=await response.json().catch(()=>null); if(!response.ok||!data?.access_token)throw new GitHubServiceError(data?.error_description||"GitHub OAuth authorization failed.","github_oauth_failed",response.status); return {accessToken:data.access_token,scope:data.scope||""};}
const getUser=token=>githubFetch("/user",{token});
async function listUserRepos(token){const repos=[];for(let page=1;page<=5;page++){const data=await githubFetch(`/user/repos?per_page=100&page=${page}&sort=updated&direction=desc`,{token});if(!Array.isArray(data)||!data.length)break;repos.push(...data);if(data.length<100)break;}return repos.map(r=>({id:r.id,owner:r.owner?.login,name:r.name,fullName:r.full_name,private:!!r.private,defaultBranch:r.default_branch||"main",htmlUrl:r.html_url,description:r.description||""}));}
async function getRepoTree(token,owner,repo,branch){return githubFetch(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/trees/${encodeURIComponent(branch)}?recursive=1`,{token});}
async function getFileContent(token,owner,repo,filePath,branch){return githubFetch(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/contents/${filePath.split("/").map(encodeURIComponent).join("/")}?ref=${encodeURIComponent(branch)}`,{token,raw:true,headers:{Accept:"application/vnd.github.raw+json"}});}
module.exports={GitHubServiceError,buildOAuthUrl,exchangeCodeForToken,getUser,listUserRepos,getRepoTree,getFileContent};
