const path=require("path"); const {REPO_ANALYZABLE_EXTENSIONS,IGNORED_PATH_PARTS,MAX_TREE_ENTRIES,MAX_CANDIDATE_FILES,MAX_SOURCE_FILE_BYTES,MAX_TOTAL_SOURCE_CHARS}=require("../../config/githubPolicy");
const STOP_WORDS=new Set(["the","and","with","from","this","that","does","not","work","working","page","application","issue","problem"]); const COMMON_PRIORITY_NAMES=["app","main","index","api","server","client","routes","controller","service","component"];
function tokenize(text){return String(text||"").toLowerCase().split(/[^a-z0-9]+/).filter(t=>t&&t.length>2&&!STOP_WORDS.has(t));}
function shouldIgnore(filePath){return filePath.split("/").some(p=>IGNORED_PATH_PARTS.has(p));}
function isAnalyzable(filePath){return REPO_ANALYZABLE_EXTENSIONS.has(path.extname(filePath).toLowerCase());}
function languageFor(filePath){return path.extname(filePath).slice(1)||"text";}
function rankTreeEntries(entries,title,description){const tokens=tokenize(`${title} ${description}`);return entries.filter(e=>e?.type==="blob"&&e.path&&!shouldIgnore(e.path)&&isAnalyzable(e.path)&&(e.size==null||e.size<=MAX_SOURCE_FILE_BYTES)).slice(0,MAX_TREE_ENTRIES).map(e=>{const lower=e.path.toLowerCase(),base=path.basename(lower,path.extname(lower)),parts=tokenize(`${lower.replaceAll("/"," ")} ${base.replaceAll(/[-_.]/g," ")}`);let score=0;for(const token of tokens){if(parts.includes(token))score+=5;else if(lower.includes(token))score+=2;}if(COMMON_PRIORITY_NAMES.includes(base))score+=1;if(lower.includes("test")||lower.includes("spec"))score-=0.5;return {...e,score};}).sort((a,b)=>b.score-a.score||a.path.length-b.path.length).slice(0,MAX_CANDIDATE_FILES);}
function capTotal(files){let remaining=MAX_TOTAL_SOURCE_CHARS,truncated=false,selected=[];for(const file of files){if(remaining<=0){truncated=true;break;}const content=file.content||"";if(content.length>remaining){selected.push({...file,content:content.slice(0,remaining)});truncated=true;remaining=0;break;}selected.push(file);remaining-=content.length;}return {files:selected,truncated};}
module.exports={tokenize,shouldIgnore,isAnalyzable,languageFor,rankTreeEntries,capTotal};
